// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrmOm9zCXJ9jzgUXlBqrfQJH2YzX0b1w4',
    appId: '1:1029108463023:web:49aad4cd57a74dc6b26b5a',
    messagingSenderId: '1029108463023',
    projectId: 'stylesnap-ai-cc2c1',
    authDomain: 'stylesnap-ai-cc2c1.firebaseapp.com',
    storageBucket: 'stylesnap-ai-cc2c1.firebasestorage.app',
    measurementId: 'G-16253EBGMC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMcu3NTTDvNyZAGcRWc4AQFakX8OQazi0',
    appId: '1:1029108463023:android:f024c6b3fe0ae226b26b5a',
    messagingSenderId: '1029108463023',
    projectId: 'stylesnap-ai-cc2c1',
    storageBucket: 'stylesnap-ai-cc2c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUfyuwgXpNPueKnquvk0DGK12xQKYbyMw',
    appId: '1:488400711485:ios:4d9be88d5410cd204cdf54',
    messagingSenderId: '488400711485',
    projectId: 'stylesnap-ai-4cb1f',
    storageBucket: 'stylesnap-ai-4cb1f.firebasestorage.app',
    iosBundleId: 'com.example.stylesnapAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUfyuwgXpNPueKnquvk0DGK12xQKYbyMw',
    appId: '1:488400711485:ios:4d9be88d5410cd204cdf54',
    messagingSenderId: '488400711485',
    projectId: 'stylesnap-ai-4cb1f',
    storageBucket: 'stylesnap-ai-4cb1f.firebasestorage.app',
    iosBundleId: 'com.example.stylesnapAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlmLnIB58spx5m4QjkCyNsOmLaYONFoGg',
    appId: '1:488400711485:web:7f294d1dce96c9b74cdf54',
    messagingSenderId: '488400711485',
    projectId: 'stylesnap-ai-4cb1f',
    authDomain: 'stylesnap-ai-4cb1f.firebaseapp.com',
    storageBucket: 'stylesnap-ai-4cb1f.firebasestorage.app',
    measurementId: 'G-NJJQ9HSLG4',
  );
}